Sprint 11
boyegorka/ImageFeed pull request #4
Opened 2023-04-06 17:53 UTC by boyegorka

Получается информация для профиля
Получается картинка для профиля
Картинка профиля грузится с помощью Kingfisher
Токен пользователя шифруется с помощью Keychain
Устранена гонка при работе с сетью
SplashScreen реализован с помощью кода
Логика TabBar реализована в коде

2023-04-07 06:02 UTC, protos17 requested changes

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/App/SceneDelegate.swift
>          // This delegate does not imply the connecting scene or session are new (see `application:configurationForConnectingSceneSession` instead).
Лишние закомментированный код рекомендую удалять

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/Services/ProfileImageService.swift
> +                print("profile image")
Notification нужно вызывать здесь, после успешного получения картинки

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/Services/ProfileImageService.swift
> +                print(profileImageURL)
Здесь необходимо указать self перед profileImageURL

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                presentAuthViewController()
Здесь необходимо указать совместно с self

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/Services/OAuth2TokenStorage.swift
>  class OAuth2TokenStorage {
Рекомендую указать класс как final

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/Services/OAuth2TokenStorage.swift
> +    let keyToken = "AuthToken"
Здесь стоит указать как private

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +    func presentAuthViewController() {
Здесь стоит добавить `private`
Необходимо указывать private  для того, чтобы спрятать детали реализации конкретной части функциональности, 
когда они используются только внутри области объявления.

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +    func setupScreen() {
Рекомендую указать как private

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +    func checkFirstStart() {
Здесь тоже советую указать как private

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +    func switchToTabBarController() {
Рекомендую указать как private

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +        guard let window = UIApplication.shared.windows.first else { fatalError("Invalid configuration") }
По своему опыту хотел бы отметить, что в продакшене не используют fatalError, советую заменить на assertionFailure.

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                let alert = UIAlertController(title: "Что-то пошло не так", message: "Не удалось войти в систему", preferredStyle: .alert)
Рекомендую вынести в отдельный метод

2023-04-07 06:02 UTC, protos17 commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                let image = ProfileImageService.shared.fetchProfileImageURL(username: self.profileService.savedProfile!.username) { _ in }
Константу image рекомендую удалить, она формата ()

2023-04-07 11:55 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                presentAuthViewController()
Вы указали, что без этого приложение не запускалось, разве это так? Я поставил self, но оно как работало, так и работает, не понимаю, если xcode его пропустил, получается, ошибок нет?

2023-04-07 12:48 UTC, protos17 commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                presentAuthViewController()
Скорее всего, новый xcode уже не подсвечивает такие моменты, прошу все равно добавить self, чтобы не возникало таких ошибок и у других ревьюеров

2023-04-08 15:08 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                presentAuthViewController()
> Скорее всего, новый xcode уже не подсвечивает такие моменты, прошу все равно добавить self, чтобы не возникало таких ошибок и у других ревьюеров

Проверь пожалуйста

2023-04-08 16:19 UTC, IBDesignable commented
Ты сделал доп фичу: выход из профиля, круто что разобрался как удалять токен, но после повторной авторизации не получается перейти на главный экран. Я не нашла строчки, где возникает ошибка, но ее нужно исправить (по крайней мере в следующем спринте это будет критично)
![RocketSim_Recording_iPhone_14_Pro_Max_2023-04-08_19 16 51](https://user-images.githubusercontent.com/121577115/230731827-3b5f07cf-42bf-40c2-b569-e4ad7ce24340.gif)

2023-04-08 16:19 UTC, IBDesignable requested changes

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/Services/OAuth2Service.swift
> +        lastCode = code
Здесь получилась большая и сложная конструкция, в учебнике есть вариант с упрощением  – выйдет и короче, и понятнее. Предлагаю вернуться здесь и обновить код)

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/Services/NetworkService.swift
> +                    fulfillCompletion(.success(data as! Data))
Я не смогу принять проект с форс анврапом, потому что data типа `Foundation.Data` небезопасно приводить к дженирик типу `Data: Decodable`. 

Тут конечно будут проблемы с декодингом, потому что декодинга здесь не произошло :) При этом по объявлению типа функции я вижу, что хотелось использовать дженерик, тогда в реализации есть ошибки.

Первое что рекомендую сделать: заменить название дженерика `Data: Decodable` на `Object: Decoable` или `T: Decodable`. Иначе можно запутаться и не понять к какому типу приводим данные. 

Затем доделать эту функцию: 
Здесь нужно было создать декодер, или воспользоваться предварительно созданным, и попробовать декодировать данные к типу. 

```swift
let decoder = JSONDecoder()
let object = try? decoder.decode(Object.self, from: data)
```
Обращу внимание, что привести тип может не получится, и операция `try?` возвращает опционал, который нужно будет еще распаковать и вернуть в случае опционала соответствующую ошибку. 

Однако, я также вижу удачное решение, что декодинг сделан отдельно для каждого сервиса: 

```swift
   private func object(for request: URLRequest, completion: @escaping (Result<OAuthTokenResponseBody, Error>) -> Void) -> URLSessionTask {
        let decoder = JSONDecoder()
        return urlSession.data(for: request) { (result: Result<Data, Error>) in
            let response = result.flatMap { data -> Result<OAuthTokenResponseBody, Error> in
                Result { try decoder.decode(OAuthTokenResponseBody.self, from: data) }
            }
            completion(response)
        }
    }
```
Если оставлять декодинг как есть, то тогда лучше в этой функции избавиться от дженерика :)  Это второй путь решения здесь. 

В итоге, это место нужно исправить к следующей сдаче работы на ревью

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/Services/NetworkService.swift
> +    func data <Data: Decodable>   (for request: URLRequest, completion: @escaping (Result<Data, Error>) -> Void) -> URLSessionTask {
Пробелы лишние, принято вот так:
```suggestion
    func data<Data: Decodable>(for request: URLRequest, completion: @escaping (Result<Data, Error>) -> Void) -> URLSessionTask {
```

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/Services/OAuth2TokenStorage.swift
>          }
предлагаю KeychainWrapper сохранить как своство класса. И придерживаться такого правила для любых зависимостей сервисов: так будет проще внедрять DI (тема непростая, познакомиться можно [здесь](https://habr.com/ru/companies/tinkoff/articles/546360/)).

Старайся адаптировать под эти правила код, так формируются правильные привычки, будет легче рефакторить под новые знания

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/Services/ProfileImageService.swift
> +                    .post(name: ProfileImageService.didChangeNotification, object: self, userInfo: ["URL" : profileImageURL])
Пришлось добавить, чтобы запустить проект. Давай доправим, чтобы у других ревьюверов не было проблем. В swift <5.7 внутри замыкания обращаться к свойствам класса нужно через `self`, новое API языка не всем еще доступно :)
```suggestion
                self.profileImageURL = data.profileImage.large
                completion(.success(true))
                NotificationCenter.default
                    .post(name: ProfileImageService.didChangeNotification, object: self, userInfo: ["URL" : self.profileImageURL])
```

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/Services/ProfileService.swift
> +        task.resume()
вообще функция .data(for: request) уже делает task.resume(). Предлагаю тогда там убрать, чтобы здесь явно прочитывались намеренья. Либо удалять повторный запуск по всему проекту.

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/Services/ProfileService.swift
> +    }
Обычно модель, которую используют в презентационном слое, выносят в отдельный файл: в данном случае это было бы верно для Profile.

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/Services/ProfileService.swift
> +    }
Здесь не очень правильная композиция логики: обнуление токена сделано вроде даже верно, а вот навигация на экран SplashViewController – уже нет. Это презентационная логика и ее лучше разместить во вьюконктроллере

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +    private let profileController = ProfileViewController()
Создавать контроллеры нужно только в момент перехода на них и размещения в иерархии на window. В данном случае для profileController и authViewController ты потратишь ресурсы на создание экранов, которые возможно и отображать не придется, к тому же такое обращение к данным чаще всего приводит к утечкам памяти. 

Давай здесь, и если где-то еще так делаешь – это уберем, и сделаем инициализацию контроллеров в навигационных методах. (перед present(_, animated: true)

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                let alert = UIAlertController(title: "Что-то пошло не так", message: "Не удалось войти в систему", preferredStyle: .alert)
Присоединюсь к комментарию, мы уже знаем как работать универсально с алертом через презентеры, поэтому можно переиспользовать опыт из MovieQuiz

2023-04-08 16:19 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                ProfileImageService.shared.fetchProfileImageURL(username: self.profileService.savedProfile!.username) { _ in }
Давай здесь внесем правки:

1) поменяем местами, чтобы гарантировать что запрос на аватар уйдет. И только потом навигировать на главный экран. 
2) ты здесь обращается сильно захватываешь self, и еще обращаешься к self свойству. Это не ок, это потенциальная утечка памяти, нужно все таки ссылку ослабить
3) `self.profileService.savedProfile!.username` — любые форс анврапы, форс касты нежелательны. Они приводят к ошибкам и не показывают твое умение с ними обращаться – для меня как нанимающего менеджера такая работа будет выглядеть слабой. Поэтому не ленись разворачивать опционалы полностью

2023-04-08 16:26 UTC, boyegorka commented on ImageFeed/Services/NetworkService.swift
> +                    fulfillCompletion(.success(data as! Data))
Круто что два разных ревьюера нашли два разных способа не принять у меня проект 😊👍

2023-04-09 14:08 UTC, boyegorka commented on ImageFeed/Services/ProfileService.swift
> +        task.resume()
Почему в учебнике оно есть?

2023-04-09 14:33 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                ProfileImageService.shared.fetchProfileImageURL(username: self.profileService.savedProfile!.username) { _ in }
Мне нужно вернуть что-то в случае если у меня всё же нет ника, я в таком случае просто ставлю пустые ковычки или мне ещё раз функцию вызвать?

2023-04-09 15:36 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +    private let profileController = ProfileViewController()
У меня только один такой случай, один present во всём splashViewController, я правильно понимаю, что я все эти свойства, в которые присвоены классы должен вызывать там где они используются?

2023-04-09 16:32 UTC, boyegorka commented on ImageFeed/Services/NetworkService.swift
> +                    fulfillCompletion(.success(data as! Data))
Так мне не обязательно использоваться дженерик? Он был в учебнике, я думал что он нужен

2023-04-09 18:29 UTC, boyegorka commented on ImageFeed/Services/ProfileService.swift
> +    }
Я доделаю это в следующем спринте, когда будем это делать

2023-04-09 19:36 UTC, IBDesignable commented on ImageFeed/Services/NetworkService.swift
> +                    fulfillCompletion(.success(data as! Data))
@boyegorka хорошо бы попробовать разобраться с темой: это очень удобно для одинаковых задач, а запросы в сеть – как раз одна из таких.
Но обязательности нет в работе. Я советую писать понятный код, если сейчас дженерики сложно даются

2023-04-09 19:37 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +    private let profileController = ProfileViewController()
Не вызывать, а создавать, свойств с вью контроллерами быть не должно @boyegorka

2023-04-09 19:38 UTC, boyegorka commented on ImageFeed/Services/NetworkService.swift
> +                    fulfillCompletion(.success(data as! Data))
Ну я понял, что мне нужно просто свой тип указать, но я не понял, к чему его дали в тот момент

2023-04-09 19:39 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +    private let profileController = ProfileViewController()
Понятно

2023-04-09 19:40 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                ProfileImageService.shared.fetchProfileImageURL(username: self.profileService.savedProfile!.username) { _ in }
Хорошим решением будет получить имя профиля, если есть – то делать запрос, если нет – показать ошибку, или пойти дальше. Это зависит от требований к продукту и плавному флоу для пользователя. Помогает выбирать решение с точки зрения пользовательского опыта, если в ТЗ четко неоговорены требования и не у кого уточнить.

2023-04-09 19:41 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +    //private let authViewController = AuthViewController()
Можно наверное удалить закомментированные контроллеры, а с сервисом определиться – нужен он или нет

2023-04-09 19:43 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +    //private let authViewController = AuthViewController()
Ну, всё что закоментировано - не используется, я так полагаю, что можно всё удалять

2023-04-09 19:44 UTC, IBDesignable approved these changes

2023-04-09 19:44 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                alertPresenter.show(result: viewModel)
Здесь снова пропущен self: нужно добавить, чтобы у других ревьюверов не возникло проблем при проверке твоего кода.
У меня тоже не запустится, но я понимаю природу ошибки и готова принять без дополнительных правок

2023-04-09 19:44 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                ProfileImageService.shared.fetchProfileImageURL(username: profileService.savedProfile?.username ?? "") { _ in }
в целом ОК решение на текущий момент. О том как это обрабатывать в идеале ответила выше

2023-04-09 19:45 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                alertPresenter.show(result: viewModel)
Я скачал версию 14.2, там мне указало ошибку только в одном месте, какой версией пользуетесь вы?

2023-04-09 19:47 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                ProfileImageService.shared.fetchProfileImageURL(username: profileService.savedProfile?.username ?? "") { _ in }
> в целом ОК решение на текущий момент. О том как это обрабатывать в идеале ответила выше

А что нужно делать если нет имени? Мы же не должны в этот момент запрос отправлять ещё один?

2023-04-09 19:48 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                ProfileImageService.shared.fetchProfileImageURL(username: profileService.savedProfile?.username ?? "") { _ in }
> > в целом ОК решение на текущий момент. О том как это обрабатывать в идеале ответила выше
> 
> А что нужно делать если нет имени? Мы же не должны в этот момент запрос отправлять ещё один?

Точнее картинка не загрузилась

2023-04-09 19:52 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                ProfileImageService.shared.fetchProfileImageURL(username: profileService.savedProfile?.username ?? "") { _ in }
если нет имени – запрашивать картинку бессмысленно, хотя в этом решении именно так и может произойти (например, если профиль забыли сохранить в переменную). 

Тогда и картинка не загрузится. 
В этом случае, можно попробовать еще раз запросить профиль, картинку, когда откроется экран профиля (на didAppear).

Если совсем ничего не получим – показывать плейсхолдер. Увы, иногда изображения не приходят и приходится показывать заглушки

2023-04-09 19:55 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                alertPresenter.show(result: viewModel)
Version 14.2, но если стоит новая, то возможно глобально используется свежая версия языка. Проверить можно введя в терминале команду: xcrun swift -version`

`swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)` – у меня 5.7.2

2023-04-09 19:56 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                ProfileImageService.shared.fetchProfileImageURL(username: profileService.savedProfile?.username ?? "") { _ in }
> если нет имени – запрашивать картинку бессмысленно, хотя в этом решении именно так и может произойти (например, если профиль забыли сохранить в переменную).
> 
> Тогда и картинка не загрузится. В этом случае, можно попробовать еще раз запросить профиль, картинку, когда откроется экран профиля (на didAppear).
> 
> Если совсем ничего не получим – показывать плейсхолдер. Увы, иногда изображения не приходят и приходится показывать заглушки

Ну, заглушка там есть, а дальше я 🤷‍♂️

2023-04-09 19:58 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                alertPresenter.show(result: viewModel)
> Version 14.2, но если стоит новая, то возможно глобально используется свежая версия языка. Проверить можно введя в терминале команду: `xcrun swift -version`
> 
> `swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)` – у меня 5.7.2

Ну, у меня 5.8:  1.75.2 Apple Swift version 5.8 (swiftlang-5.8.0.124.1 clang-1403.0.22.11.100)

2023-04-09 19:59 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                alertPresenter.show(result: viewModel)
Как в такие моменты работать? У меня всё работает, а у вас нет

2023-04-09 20:10 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                alertPresenter.show(result: viewModel)
Где именно в пулреквесте оставлять версию xcode? Делать коментарий или внутри комита?

2023-04-09 20:26 UTC, boyegorka commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                alertPresenter.show(result: viewModel)
Со сменой версии xcode меняется версия языка, могу проверять совместимость, тем не менее, мне не указало ошибку в том месте, где она у тебя

2023-04-10 07:10 UTC, IBDesignable commented on ImageFeed/ViewControllers/SplashScreen/SplashViewController.swift
> +                alertPresenter.show(result: viewModel)
Вот здесь будет достаточно:
<img width="920" alt="Снимок экрана 2023-04-10 в 10 06 44" src="https://user-images.githubusercontent.com/121577115/230847028-50979a95-d0a3-45c9-964c-09c6db4fa06c.png">

Егор, я сообщила об этом команде, мы придумаем как в этом случае работать. Версия языка не обновляется с каждой версией Xcode, мы сталкиваемся с этим первый раз. 

В командах разработки обычно фиксируют окружение: версию языка, Xcode и другие зависимости. Чтобы у членов команды были одинаковые условия и проект собирался одинаково. К сожалению, требования у курса фиксировались условно "давно" и их нужно обновлять. Мы проработаем этот пункт. А сейчас придется такой костыль поставить, если тебе не сложно, конечно же

2023-04-10 10:19 UTC, merged